// <auto-generated />
namespace SPANTech.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _dateproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_dateproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202205110407495__dateproperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
